### ISSUE TITLE
demo datasets

### ISSUE THREAD

**Issue by ZhanYangen** [deng-ai-lab/soScope#1]
你好，请问能提供一下demo代码中使用到的数据集文件吗？

**Comment by bohanLi-98** [comment]
你好，可在 https://www.dropbox.com/scl/fo/igdq4lf0kzlnt5z3ddugs/h?rlkey=wjjdcv05d4b0dsreu0cxon415&e=1&st=daumer1d&dl=0 下载

**Comment by ZhanYangen** [comment]
非常感谢
