### ISSUE TITLE
Spatial multi-omics datasets preprocessing

### ISSUE THREAD

**Issue by zouwanpeng** [deng-ai-lab/soScope#2]
Hello，

Thank you for proposing such a fantastic model！I am currently working with spatial multi-omics data, specifically the Human skin dataset from the spatial-CITE-seq platform. However, I am unclear on how to preprocess this dataset after downloading it from the link provided in your paper. Could you please share the preprocessing steps or provide guidance on how to approach the preprocessing for this dataset?

Best regards!

**Comment by bohanLi-98** [comment]
We use the raw count data for soScope, because soScope is designed to regress the original count with specific distribution. If you want to preprocess spatial-CITE-seq data, please refer to https://github.com/edicliuyang/Hiplex_proteome/tree/main/Rawdata_processing

**Comment by bohanLi-98** [comment]
Also, if

**Comment by bohanLi-98** [comment]
We use the raw count data for spatial-CITE-seq, because soScope is designed to regress the original count with specific distribution. If you want to preprocess spatial-CITE-seq data, please refer to https://github.com/edicliuyang/Hiplex_proteome/tree/main/Data_visualization
